/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
static yyconst short int yy_accept[315] =
    {   0,
       36,   36,   72,   70,   40,   44,   70,   70,   70,   67,
       70,   59,   60,   65,   64,   57,   63,   66,   36,   36,
       54,   68,   58,   69,   36,   61,   62,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   55,   70,   56,   40,   53,    0,   43,    0,
        0,    0,   48,   46,   42,   42,   45,   47,    0,   38,
       36,   36,   36,    0,   50,   52,   51,   36,   36,   36,
       36,   36,   36,    8,   36,   36,   36,   36,   36,   36,
       17,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   49,    0,    0,    0,    0,   38,   36,   36,

       36,   41,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   15,   36,   36,   19,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,    0,    0,   39,   36,   36,   36,    1,
       36,    3,    4,   36,   36,   36,   36,   11,   12,   36,
       36,   16,   36,   20,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   33,   36,   36,    0,
        0,   36,   36,   36,    2,    5,   36,   36,   36,    0,
       36,   14,   36,   36,   36,   36,   24,   36,   36,   36,
       36,   36,   36,   31,   36,   36,   35,    0,    0,   36,

       36,   36,   36,   36,    9,    0,   13,   18,   36,   36,
       23,   25,   26,   27,   28,   29,   36,   36,   36,   37,
        0,   36,   36,   36,   36,    7,   10,   36,   36,   30,
       36,   36,    0,   36,   36,   36,    6,   21,   22,   32,
       34,    0,    0,   36,   36,   36,    0,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,

       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   25,   24,   24,
       26,   27,   28,    1,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   24,   39,   40,   41,   42,
       43,   44,   24,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[57] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    4,    4,    1,
        1,    1,    3,    5,    5,    1,    1,    1,    4,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    6,    1
    } ;

static yyconst short int yy_base[349] =
    {   0,
        0,    0,  670,  671,   55,  671,  647,   52,   27,  671,
      659,  671,  671,  671,   48,  671,   53,   52,   55,   44,
      671,  645,  644,  643,  609,  671,  671,   22,   30,   52,
       47,   46,   53,   48,   63,   49,   60,   74,   32,   58,
       71,   72,  671,  608,  671,  115,  671,  110,  671,  659,
      627,  618,  671,  671,  113,  104,  671,  671,  647,    0,
      115,    0,  117,  123,  671,  671,  671,  611,  623,  610,
      625,  612,  618,  604,  605,  602,  602,  605,  602,  599,
        0,   99,  603,  123,  601,   92,   95,  605,  598,  125,
      122,  603,  671,  605,  607,  626,   66,    0,  125,    0,

      147,  154,  594,  606,  601,  589,  128,  603,  601,  597,
      589,  595,  598,    0,  584,  588,    0,  589,  586,  576,
      574,  576,  578,  585,  571,  569,  569,  581,  571,  575,
      579,  581,  570,  526,  504,  671,  172,    0,  174,    0,
      476,    0,    0,  467,  475,  464,  469,  504,    0,  462,
      459,    0,  449,    0,  444,  444,  443,  438,  450,  440,
      444,  435,  434,  432,  422,  425,    0,  413,  425,  416,
      395,  176,    0,  180,    0,    0,  400,  401,  406,  399,
      394,    0,  401,  387,  381,  376,    0,  384,  381,  381,
      365,  374,  376,    0,  353,  356,    0,  359,  359,  178,

        0,  198,  341,  341,    0,  352,    0,    0,  352,  339,
        0,    0,    0,    0,    0,    0,  335,  211,  184,  671,
      184,  182,    0,  204,  169,    0,  671,  138,  129,    0,
      134,  127,  198,  202,    0,  222,    0,    0,    0,    0,
        0,  221,  107,  208,    0,  228,   97,  225,    0,  246,
      230,    0,  252,  232,    0,  270,  248,    0,  276,  250,
        0,  294,  254,    0,  300,  256,    0,  318,  272,    0,
      324,  274,    0,  342,  278,    0,  348,  280,    0,  366,
      296,    0,  372,  298,    0,  390,  302,    0,  396,  304,
        0,  414,  320,    0,  420,  322,    0,  438,  326,    0,

      444,  328,    0,  462,  344,    0,  468,  346,    0,  486,
      350,  671,  492,  671,  527,  530,  536,  542,  545,  547,
      549,  551,  553,  555,  557,  560,  562,  564,  566,  568,
      570,  572,  574,  576,  578,  580,  582,  584,  586,  588,
      590,  592,  594,  596,  598,  600,  602,  604
    } ;

static yyconst short int yy_def[349] =
    {   0,
      314,    1,  314,  314,  314,  314,  314,  315,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  316,  316,
      314,  314,  314,  314,  316,  314,  314,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  314,  314,  314,  314,  314,  315,  314,  315,
      314,  314,  314,  314,  314,  314,  314,  314,  317,  318,
      319,  319,  319,  314,  314,  314,  314,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  314,  314,  314,  317,  317,  318,  320,  320,

      320,  314,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  314,  314,  314,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  314,
      314,  322,  322,  322,  322,  322,  322,  322,  322,  314,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  314,  314,  323,

      323,  323,  323,  323,  323,  314,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  314,
      314,  324,  324,  324,  324,  324,  314,  324,  324,  324,
      324,  324,  314,  325,  325,  325,  325,  325,  325,  325,
      325,  314,  326,  327,  327,  327,  326,  328,  328,  328,
      329,  329,  329,  330,  330,  330,  331,  331,  331,  332,
      332,  332,  333,  333,  333,  334,  334,  334,  335,  335,
      335,  336,  336,  336,  337,  337,  337,  338,  338,  338,
      339,  339,  339,  340,  340,  340,  341,  341,  341,  342,
      342,  342,  343,  343,  343,  344,  344,  344,  345,  345,

      345,  346,  346,  346,  347,  347,  347,  348,  348,  348,
      314,  314,  314,    0,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314
    } ;

static yyconst short int yy_nxt[728] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,    4,   18,   19,   20,   21,
       22,   23,   24,   25,   25,   26,    4,   27,   25,   28,
       29,   30,   31,   32,   33,   34,   25,   35,   25,   36,
       25,   25,   25,   25,   37,   38,   39,   40,   41,   42,
       25,   25,   25,   43,   44,   45,   46,   49,   46,   51,
       54,   61,   61,   59,   52,   55,   56,   57,   60,   68,
       55,   56,   61,   61,   69,   58,  314,   97,   50,   63,
       73,   70,  136,   89,  314,   75,  314,   76,   71,   74,
       80,   83,   78,   84,   72,   79,   77,   81,  314,   90,

      314,  314,  314,  314,   82,   63,  314,  314,   92,   64,
       85,   86,  314,   91,  314,   49,   46,  314,   46,  220,
       87,   56,   56,   88,  125,  314,  314,  123,  314,  220,
       56,   56,   99,   99,  101,  101,   50,   64,  116,  126,
      102,  102,  137,  137,  124,  117,  101,  101,  101,  101,
      101,  101,  102,  102,  102,  102,  102,  102,  119,  131,
      241,  132,  129,   64,  139,  139,  240,   64,  120,  121,
      130,  102,  102,  144,  145,  239,  139,  139,  139,  139,
      139,  139,  238,  102,  102,  102,  102,  102,  102,  172,
      172,  174,  174,  200,  200,  222,  222,  202,  202,  234,

      234,  242,  237,  174,  174,  174,  174,  174,  174,  202,
      202,  202,  202,  202,  202,  224,  224,  233,  243,  244,
      244,  236,  236,  232,  242,  248,  248,  224,  224,  224,
      224,  224,  224,  236,  236,  236,  236,  236,  236,  246,
      246,  243,  251,  251,  231,  250,  250,  254,  254,  257,
      257,  246,  246,  246,  246,  246,  246,  250,  250,  250,
      250,  250,  250,  253,  253,  260,  260,  263,  263,  256,
      256,  266,  266,  269,  269,  253,  253,  253,  253,  253,
      253,  256,  256,  256,  256,  256,  256,  259,  259,  272,
      272,  275,  275,  262,  262,  278,  278,  281,  281,  259,

      259,  259,  259,  259,  259,  262,  262,  262,  262,  262,
      262,  265,  265,  284,  284,  287,  287,  268,  268,  290,
      290,  293,  293,  265,  265,  265,  265,  265,  265,  268,
      268,  268,  268,  268,  268,  271,  271,  296,  296,  299,
      299,  274,  274,  302,  302,  305,  305,  271,  271,  271,
      271,  271,  271,  274,  274,  274,  274,  274,  274,  277,
      277,  308,  308,  311,  311,  280,  280,   56,   56,  230,
      229,  277,  277,  277,  277,  277,  277,  280,  280,  280,
      280,  280,  280,  283,  283,  228,  227,  226,  225,  286,
      286,  221,  220,  219,  218,  283,  283,  283,  283,  283,

      283,  286,  286,  286,  286,  286,  286,  289,  289,  217,
      216,  215,  214,  292,  292,  213,  212,  211,  210,  289,
      289,  289,  289,  289,  289,  292,  292,  292,  292,  292,
      292,  295,  295,  209,  208,  207,  206,  298,  298,  205,
      204,  203,  199,  295,  295,  295,  295,  295,  295,  298,
      298,  298,  298,  298,  298,  301,  301,  198,  197,  196,
      195,  304,  304,  194,  193,  192,  191,  301,  301,  301,
      301,  301,  301,  304,  304,  304,  304,  304,  304,  307,
      307,  190,  189,  188,  187,  310,  310,  186,  185,  184,
      183,  307,  307,  307,  307,  307,  307,  310,  310,  310,

      310,  310,  310,  313,  313,  182,  181,  180,  179,  102,
      102,  178,  177,  176,  175,  313,  313,  313,  313,  313,
      313,  102,  102,  102,  102,  102,  102,   48,   48,   48,
       48,   48,   48,   62,   62,   62,   96,   96,   96,   96,
       96,   96,   98,  171,   98,   98,   98,   98,  100,  100,
      138,  138,  173,  173,  201,  201,  223,  223,  235,  235,
      245,  245,  247,  170,  247,  249,  249,  252,  252,  255,
      255,  258,  258,  261,  261,  264,  264,  267,  267,  270,
      270,  273,  273,  276,  276,  279,  279,  282,  282,  285,
      285,  288,  288,  291,  291,  294,  294,  297,  297,  300,

      300,  303,  303,  306,  306,  309,  309,  312,  312,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  160,  159,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  143,  142,  141,  140,   97,  135,  134,
      133,  128,  127,  122,  118,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  106,  105,  104,  103,   97,   95,
       94,  314,   93,  314,   67,   66,   65,   53,   47,  314,
        3,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,

      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314
    } ;

static yyconst short int yy_chk[728] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    8,    5,    9,
       15,   20,   20,   18,    9,   15,   15,   17,   18,   28,
       17,   17,   19,   19,   29,   17,   28,   97,    8,   19,
       31,   30,   97,   39,   29,   32,   39,   32,   30,   31,
       34,   36,   33,   37,   30,   33,   32,   35,   20,   40,

       32,   31,   34,   36,   35,   19,   30,   33,   42,   19,
       38,   38,   40,   41,   37,   48,   46,   35,   46,  247,
       38,   56,   56,   38,   87,   41,   42,   86,   38,  243,
       55,   55,   61,   61,   63,   63,   48,   55,   82,   87,
       64,   64,   99,   99,   86,   82,   63,   63,   63,   63,
       63,   63,   64,   64,   64,   64,   64,   64,   84,   91,
      232,   91,   90,   55,  101,  101,  231,   55,   84,   84,
       90,  102,  102,  107,  107,  229,  101,  101,  101,  101,
      101,  101,  228,  102,  102,  102,  102,  102,  102,  137,
      137,  139,  139,  172,  172,  200,  200,  174,  174,  222,

      222,  233,  225,  139,  139,  139,  139,  139,  139,  174,
      174,  174,  174,  174,  174,  202,  202,  221,  233,  234,
      234,  224,  224,  219,  242,  244,  244,  202,  202,  202,
      202,  202,  202,  224,  224,  224,  224,  224,  224,  236,
      236,  242,  248,  248,  218,  246,  246,  251,  251,  254,
      254,  236,  236,  236,  236,  236,  236,  246,  246,  246,
      246,  246,  246,  250,  250,  257,  257,  260,  260,  253,
      253,  263,  263,  266,  266,  250,  250,  250,  250,  250,
      250,  253,  253,  253,  253,  253,  253,  256,  256,  269,
      269,  272,  272,  259,  259,  275,  275,  278,  278,  256,

      256,  256,  256,  256,  256,  259,  259,  259,  259,  259,
      259,  262,  262,  281,  281,  284,  284,  265,  265,  287,
      287,  290,  290,  262,  262,  262,  262,  262,  262,  265,
      265,  265,  265,  265,  265,  268,  268,  293,  293,  296,
      296,  271,  271,  299,  299,  302,  302,  268,  268,  268,
      268,  268,  268,  271,  271,  271,  271,  271,  271,  274,
      274,  305,  305,  308,  308,  277,  277,  311,  311,  217,
      210,  274,  274,  274,  274,  274,  274,  277,  277,  277,
      277,  277,  277,  280,  280,  209,  206,  204,  203,  283,
      283,  199,  198,  196,  195,  280,  280,  280,  280,  280,

      280,  283,  283,  283,  283,  283,  283,  286,  286,  193,
      192,  191,  190,  289,  289,  189,  188,  186,  185,  286,
      286,  286,  286,  286,  286,  289,  289,  289,  289,  289,
      289,  292,  292,  184,  183,  181,  180,  295,  295,  179,
      178,  177,  171,  292,  292,  292,  292,  292,  292,  295,
      295,  295,  295,  295,  295,  298,  298,  170,  169,  168,
      166,  301,  301,  165,  164,  163,  162,  298,  298,  298,
      298,  298,  298,  301,  301,  301,  301,  301,  301,  304,
      304,  161,  160,  159,  158,  307,  307,  157,  156,  155,
      153,  304,  304,  304,  304,  304,  304,  307,  307,  307,

      307,  307,  307,  310,  310,  151,  150,  148,  147,  313,
      313,  146,  145,  144,  141,  310,  310,  310,  310,  310,
      310,  313,  313,  313,  313,  313,  313,  315,  315,  315,
      315,  315,  315,  316,  316,  316,  317,  317,  317,  317,
      317,  317,  318,  135,  318,  318,  318,  318,  319,  319,
      320,  320,  321,  321,  322,  322,  323,  323,  324,  324,
      325,  325,  326,  134,  326,  327,  327,  328,  328,  329,
      329,  330,  330,  331,  331,  332,  332,  333,  333,  334,
      334,  335,  335,  336,  336,  337,  337,  338,  338,  339,
      339,  340,  340,  341,  341,  342,  342,  343,  343,  344,

      344,  345,  345,  346,  346,  347,  347,  348,  348,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,
      122,  121,  120,  119,  118,  116,  115,  113,  112,  111,
      110,  109,  108,  106,  105,  104,  103,   96,   95,   94,
       92,   89,   88,   85,   83,   80,   79,   78,   77,   76,
       75,   74,   73,   72,   71,   70,   69,   68,   59,   52,
       51,   50,   44,   25,   24,   23,   22,   11,    7,    3,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,

      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\testlex.l"
#define INITIAL 0
#line 9 ".\\testlex.l"
#include<stdio.h>
int comment = 0;
int yylineno=1;
#line 638 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 13 ".\\testlex.l"


#line 792 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 315 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 671 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 15 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 17 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 19 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 20 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 21 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 22 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 23 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 24 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 25 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 26 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 27 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 28 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 29 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 30 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 31 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 32 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 33 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 34 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 35 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 36 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 37 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 38 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 39 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 40 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 41 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 42 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 43 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 44 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 45 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 46 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 47 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 48 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 49 ".\\testlex.l"
{ printf("Keyword: %s\n",yytext); } 
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 52 ".\\testlex.l"
{ printf("Identifier: %s\n",yytext);} 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 55 ".\\testlex.l"
{printf("Pre Processor: %s\n",yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 ".\\testlex.l"
{printf("Single line comment: %s \n",yytext);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 ".\\testlex.l"
{printf("Multi line comment: %s \n",yytext);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 62 ".\\testlex.l"
{}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 63 ".\\testlex.l"
{printf("Hex: %s\n", yytext);}				
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 64 ".\\testlex.l"
{printf("Constant: %s\n", yytext);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 65 ".\\testlex.l"
{printf("String literal :%s\n",yytext);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 67 ".\\testlex.l"
{yylineno++;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 69 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 70 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 71 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 72 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 73 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 74 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 75 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 76 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 77 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 78 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 79 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 80 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 81 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 82 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 83 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 84 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 85 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 86 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 87 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 88 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 89 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 90 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 91 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 92 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 93 ".\\testlex.l"
{printf("Punctuator: %s\n",yytext);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 96 ".\\testlex.l"
{printf("Line %3d: Illegal character %s\n",yylineno,yytext);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 98 ".\\testlex.l"
ECHO;
	YY_BREAK
#line 1230 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 315 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 315 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 314);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 98 ".\\testlex.l"



int yywrap()
{
	return 0;
}

int main(int argc,char **argv)
{
	if(argc>1)
	{
		FILE *file;
		yyin = fopen(argv[1],"r");
		yylex();
		fclose(yyin);
	}
	else
	{
		printf("Please enter an input file!\n");
	}
	printf("\n\n");
	return 0;
}